#!/bin/bash

export COMPOSE_CONVERT_WINDOWS_PATHS=1

# kill $(lsof -t -i:8080)
# kill -9


ntim(){
    docker-compose \
    -f ./ntim-hadoop.yml \
    "$@"
}


ntimup(){
  ntim up -d --build
  # emacs_up
}

ntimdown(){
  ntim down
  # emacs_up
}



bde2(){
    docker-compose \
    -f ./bde-hadoop.yml \
    "$@"
}


bde2up(){
  bde up -d --build
  # emacs_up
}

bde2down(){
  bde down
  # emacs_up
}

bdenginx(){
  docker-compose -f docker-hadoop/docker-compose-nginx.yml  "$@"
}

la(){
  docker-compose -f docker-hadoop/docker-compose.yml -f docker-hadoop/apps.yml  "$@"
}
laup(){
  la up -d --build
}
ladown(){
  la down
}
labash(){
  la exec namenode bash
}

larm(){
  la stop "$@"
  la rm "$@"
}
larmres(){
  larm "$@"
  larm start "$@"
}



"$@"
