#!/bin/bash

export COMPOSE_CONVERT_WINDOWS_PATHS=1

# kill $(lsof -t -i:8080)
# kill -9


ntim(){
    docker-compose \
    -f ./ntim-hadoop.yml \
    "$@"
}


ntimup(){
  ntim up -d --build
  # emacs_up
}

ntimdown(){
  ntim down
  # emacs_up
}



bde2(){
    docker-compose \
    -f ./bde-hadoop.yml \
    "$@"
}


bde2up(){
  bde up -d --build
  # emacs_up
}

bde2down(){
  bde down
  # emacs_up
}

bdenginx(){
  docker-compose -f docker-hadoop/docker-compose-nginx.yml  "$@"
}

la0(){
  docker-compose -f dc-apps.yml -f dc-docker-hadoop.yml  "$@"
  # docker-compose -f docker-hadoop/docker-compose.yml -f apps/docker-compose.yml config | docker-compose -f - up
}

la(){
  docker-compose -f dc-apps.yml -f dc-hadoop.yml "$@"
  # docker-compose -f docker-hadoop/docker-compose.yml -f apps/docker-compose.yml config | docker-compose -f - up
}

laup(){
  la up -d --build --scale datanode=3
}
ladown(){
  la down
}

b(){
  la exec "$1" bash # "${@:2}"
}
labash(){
  la exec -it "$1" bash "${@:2}"
}

larm(){
  la stop "$@"
  la rm "$@"
}

push(){
  # http://localhost:5000/v2/_catalog
  REGISTRY_HOST=localhost:5000
  echo $REGISTRY_HOST/$1
  docker image tag $1 $REGISTRY_HOST/$1
  docker push $REGISTRY_HOST/$1
}

nmcas(){
  sh c la exec nodemanager bash -c "bash c appcas; cd ../apps/app_cascalog; bash;"
}
bsh(){
  sh c la exec nodemanager bash -c "cd ../apps/batch; bash;"
}

"$@"
