version: "3.3"

services: 

  base:
    image: la.hadoop.base
    build:
      context: ./hadoop
      dockerfile: ./base/Dockerfile
    # volumes:
    #   - ./hadoop/.volumes/etc.hadoop:/usr/local/hadoop/etc/hadoop
    # command: bash c init
    command: bash c tail_dev_null
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true


  namenode:
    image: la.hadoop.namenode
    build:
      context: ./hadoop/namenode
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/namenode:/opt/code/app
    ports:
      - "19870:9870"
      - "9820:9820"
    command: bash c main
    # command: bash c tail_dev_null
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - base

  resourcemanager:
    image: la.hadoop.resourcemanager
    build:
      context: ./hadoop/resourcemanager
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/resourcemanager:/opt/code/app
    ports:
      - 18088:8088
    command: bash c main
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - base
      - namenode
      - datanode1
      - datanode2
      - datanode3


  nodemanager:
    image: la.hadoop.nodemanager
    build:
      context: ./hadoop/nodemanager
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/nodemanager:/opt/code/app
    # command: bash c init
    command: tail -f /dev/null
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - base

  webappproxy:
    image: la.hadoop.webappproxy
    build:
      context: ./hadoop/webappproxy
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/webappproxy:/opt/code/app
    # command: bash c init
    command: tail -f /dev/null
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - base

  jobhistory:
    image: la.hadoop.jobhistory
    build:
      context: ./hadoop/jobhistory
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/jobhistory:/opt/code/app
    command: bash c main
    # command: tail -f /dev/null
    env_file:
      - ./hadoop/.conf/.env
    ports:
      - "18188:19888"
    stdin_open: true
    tty: true
    links:
      - base
      - namenode
      

  datanode:
    image: la.hadoop.datanode
    build:
      context: ./hadoop/datanode
      dockerfile: ./Dockerfile
    command: bash c tail_dev_null
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - base

  datanode1:
    image: la.hadoop.datanode
    command: bash c main
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - datanode
      - namenode

  datanode2:
    image: la.hadoop.datanode
    command: bash c main
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - datanode
      - namenode

  datanode3:
    image: la.hadoop.datanode
    command: bash c main
    env_file:
      - ./hadoop/.conf/.env
    stdin_open: true
    tty: true
    links:
      - datanode
      - namenode

# volumes:
#   volume.la.hadoop.namenode:
#       external:
#         name: volume.la.hadoop.namenode

# https://docs.docker.com/compose/compose-file/#long-syntax-3
# https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

  # la.hadoop.namenode:
  #   image: la.hadoop.namenode
  #   build:
  #     context: ./hadoop/namenode
  #     dockerfile: ./Dockerfile
  #   # volumes:
  #     # - type: bind
  #     #   source: ./hadoop/.volumes/namenode/etc.hadoop
  #     #   target: /usr/local/hadoop/etc/hadoop
  #     #   read_only: false
  #     #   # bind:
  #     #   #   propagation: rshared
  #     #   volume:
  #     #     nocopy: true
        
  #     # - ./hadoop/.volumes/namenode/etc.hadoop:/usr/local/hadoop/etc/hadoop
  #   # command: bash c init
  #   command: tail -f /dev/null
  #   stdin_open: true
  #   tty: true
  #   links:
  #     - la.hadoop.base

# volumes:
#   volume.la.hadoop.namenode:
#     driver: local
#     source: /tmp/volume
#     driver_opts:
#       type: volume
      # o: 'bind'
      # mountpoint: /tmp/volume/la.hadoop.namenode
      # device: '/tmp/volumes/la.hadoop.namenode'