version: "3.3"

services: 

  la.hadoop.base:
    image: la.hadoop.base
    build:
      context: ./hadoop/base
      dockerfile: ./Dockerfile
    # volumes:
    #   - ./hadoop/.volumes/etc.hadoop:/usr/local/hadoop/etc/hadoop
    # command: bash c init
    command: tail -f /dev/null
    stdin_open: true
    tty: true


  la.hadoop.namenode:
    image: la.hadoop.namenode
    build:
      context: ./hadoop/namenode
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/.volumes/namenode/etc.hadoop:/usr/local/hadoop/etc/hadoop
    # command: bash c init
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    links:
      - la.hadoop.base