version: "3.3"

services: 

  base:
    image: la.hadoop.base
    build:
      context: ./hadoop
      dockerfile: ./base/Dockerfile
    command: tail -f /dev/null
    env_file:
      - ./.env
    stdin_open: true
    tty: true


  namenode:
    image: la.hadoop.namenode
    build:
      context: ./hadoop/namenode
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/namenode:/opt/code/app
      # - ./apps/app_cascalog:/opt/code/app_cascalog/
    ports:
      - "19870:9870"
      - "9820:9820"
      - 12556:35543
    command: bash c main
    # command: bash c tail_dev_null
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - base

  resourcemanager:
    image: la.hadoop.resourcemanager
    build:
      context: ./hadoop/resourcemanager
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/resourcemanager:/opt/code/app
    ports:
      - 18088:8088
    command: bash c main
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - base
      - namenode
      - datanode1
      - datanode2
      - datanode3


  nodemanager:
    image: la.hadoop.nodemanager
    build:
      context: ./hadoop/nodemanager
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/nodemanager:/opt/code/app
      - ./apps:/opt/code/apps
    ports:
      - 12555:35543
    command: bash c main
    # command: tail -f /dev/null
    env_file:
      - ./.env
    # privileged: true
    stdin_open: true
    tty: true
    links:
      - base
      - registry

  webappproxy:
    image: la.hadoop.webappproxy
    build:
      context: ./hadoop/webappproxy
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/webappproxy:/opt/code/app
    # command: bash c init
    command: tail -f /dev/null
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - base

  jobhistory:
    image: la.hadoop.jobhistory
    build:
      context: ./hadoop/jobhistory
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/jobhistory:/opt/code/app
    command: bash c main
    # command: tail -f /dev/null
    env_file:
      - ./.env
    ports:
      - "18188:19888"
    stdin_open: true
    tty: true
    links:
      - base
      - namenode

  timeline:
    image: la.hadoop.timeline
    build:
      context: ./hadoop/timeline
      dockerfile: ./Dockerfile
    volumes:
      - ./hadoop/timeline:/opt/code/app
    command: bash c main
    # command: tail -f /dev/null
    env_file:
      - ./.env
    ports:
      - "18288:8188"
    stdin_open: true
    tty: true
    links:
      - base
      - namenode


  registry:
    image: registry:2
    ports:
      - 5000:5000
    # environment:
    #   REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    #   REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    #   REGISTRY_AUTH: htpasswd
    #   REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    #   REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    # volumes:
    #   - /path/data:/var/lib/registry
    #   - /path/certs:/certs
    #   - /path/auth:/auth     

  datanodebase:
    image: la.hadoop.datanodebase
    build:
      context: ./hadoop/datanode
      dockerfile: ./Dockerfile
    command: bash c tail_dev_null
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - base

  datanode1:
    image: la.hadoop.datanodebase
    command: bash c main
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - datanodebase
      - namenode

  datanode2:
    image: la.hadoop.datanodebase
    command: bash c main
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - datanodebase
      - namenode

  datanode3:
    image: la.hadoop.datanodebase
    command: bash c main
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    links:
      - datanodebase
      - namenode

# volumes:
#   volume.la.hadoop.namenode:
#       external:
#         name: volume.la.hadoop.namenode

# https://docs.docker.com/compose/compose-file/#long-syntax-3
# https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

  # la.hadoop.namenode:
  #   image: la.hadoop.namenode
  #   build:
  #     context: ./hadoop/namenode
  #     dockerfile: ./Dockerfile
  #   # volumes:
  #     # - type: bind
  #     #   source: ./hadoop/.volumes/namenode/etc.hadoop
  #     #   target: /usr/local/hadoop/etc/hadoop
  #     #   read_only: false
  #     #   # bind:
  #     #   #   propagation: rshared
  #     #   volume:
  #     #     nocopy: true
        
  #     # - ./hadoop/.volumes/namenode/etc.hadoop:/usr/local/hadoop/etc/hadoop
  #   # command: bash c init
  #   command: tail -f /dev/null
  #   stdin_open: true
  #   tty: true
  #   links:
  #     - la.hadoop.base

# volumes:
#   volume.la.hadoop.namenode:
#     driver: local
#     source: /tmp/volume
#     driver_opts:
#       type: volume
      # o: 'bind'
      # mountpoint: /tmp/volume/la.hadoop.namenode
      # device: '/tmp/volumes/la.hadoop.namenode'