version: "3.3"

services:

  datomic:
    image: procloj-datomic-free
    build:
      context: ./datomic
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    stdin_open: true
    tty: true

  app:
    image: procloj-app
    volumes:
      - ./app:/opt/code/app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 5335:35543
      - 5888:7888
      - 5580:8080
    command: bash c init
    stdin_open: true
    tty: true
    links:
      - datomicdb

  app-testing:
    image: app-testing
    volumes:
      - ./professional-clojure-testing:/opt/code/app
    build:
      context: ./professional-clojure-testing
      dockerfile: ./Dockerfile
    ports:
      - 5345:35543
      - 5889:7888
      - 5581:8080
    command: bash c init
    stdin_open: true
    tty: true
    links:
      - postgresdb

  postgresdb:
    image: postgres:11.1
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fincalc
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    # restart: always
    ports:
      - 5582:8080
    links:
      - postgresdb:db

  datomicdb:
    image: procloj-datomic-free
    # ports:
      # - "4436:4336"
      # - "4435:4335"
      # - "4434:4334"
      # - "9000:9000"
    command: ./bin/transactor ./config/free-transactor.properties
    stdin_open: true
    tty: true
    depends_on:
      - datomic

  # ui:
  #   image: proclj-ui
  #   volumes:
  #     - ./ui:/clj
  #   build:
  #     context: ./ui
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 3449:3449
  #     - 7788:7888
  #   command: bash c init
  #   stdin_open: true
  #   tty: true
  #   links:
  #     - app


  whip:
    image: whip
    # container_name: dq-dockerwheel
    volumes:
      - ./whip:/opt/code/app
    build:
      context: ./whip
      dockerfile: ./Dockerfile
    ports:
      - 3449:3449
      - 5355:35543
    # command: tail -f /dev/null
    # command: lein do clean, figwheel
    command: bash c init
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
