#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9

main(){
  start
  tail_dev_null
}
start(){
  # hdfs datanode -h
 $HADOOP_HOME/bin/yarn --daemon start resourcemanager
}

tail_dev_null(){
  tail -f /dev/null
}


"$@"
