#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9

main(){
  service ssh start &
  start
  # tail_dev_null
}
start_daemon(){
  # hdfs datanode -h
 $HADOOP_HOME/bin/yarn --daemon start resourcemanager
}
start(){
  $HADOOP_HOME/bin/yarn --config $HADOOP_CONF_DIR resourcemanager
}

tail_dev_null(){
  tail -f /dev/null
}


"$@"
