FROM la.hadoop.base





# yarn.resourcemanager.scheduler.address
EXPOSE 8030 

# yarn.resourcemanager.resource-tracker.address
EXPOSE 8031

# yarn.resourcemanager.address
EXPOSE 8032

# yarn.resourcemanager.webapp.address
EXPOSE 8088



