#!/bin/bash

# export $(grep -v '^#' /opt/.env | xargs)

repl(){
  # lein repl :headless :host 0.0.0.0 :port 35543
  lein repl :start :host 0.0.0.0 :port 35543
}

repl_headless(){
  lein repl :headless :host 0.0.0.0 :port 35543
}

ring_headless(){
   lein ring server-headless 
}

conn(){
  lein repl :connect 0.0.0.0:35543
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

test(){
  lein test
}

test_refresh(){
  lein test-refresh
}

main(){
  #  repl_headless
  # lein auto javac &
  lein run-dev
}

uberjar(){
  lein ring uberjar
}


uberwar(){
  lein ring uberwar
}


set_env(){
  # export $(cat .env | xargs) && rails c
  export $(grep -v '^#' /opt/.env | xargs)

}

unset_env(){
  unset $(grep -v '^#' .env | sed -E 's/(.*)=.*/\1/' | xargs)
}

uber(){
  java -jar target/la.app_cascalog-0.1.0-SNAPSHOT-standalone.jar
}

uberh(){
  hadoop jar target/la.app_cascalog-0.1.0-SNAPSHOT-standalone.jar
}

"$@"
