#!/bin/bash

repl(){
  # lein repl :headless :host 0.0.0.0 :port 35543
  lein repl :start :host 0.0.0.0 :port 35543
}

repl_headless(){
  lein repl :headless :host 0.0.0.0 :port 35543
}

test(){
  lein test
}

test_refresh(){
  lein test-refresh
}

dev(){
  #  repl_headless
  lein dev
}

uberjar(){
  # lein with-profile wordcount:sandbox:cascalog uberjar
  lein with-profile wordcount uberjar
}


hadjar(){
  hadoop jar target/$1-standalone.jar  "${@:2}"
}

jobwc(){
  hadjar wordcount out11
}


"$@"
