#!/bin/bash


la() {
    docker build -t csbooks.la .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name la \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)"/lab:/opt/app \
                 csbooks.la \
                 bash
}

"$@"