#!/bin/bash

connlein(){
    lein repl :connect  nrepl://127.0.0.1:$1
}

connclj(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"}}}' -m nrepl.cmdline --connect --host 0.0.0.0 --port $1
}

mem(){
  top -b -o +%MEM |head -30
}

la() {
    docker build -t csbooks.la .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name la \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)"/lab:/opt/app \
                 csbooks.la \
                 bash
}

"$@"