#!/bin/bash

repl(){
  # lein repl :headless :host 0.0.0.0 :port 35543
  lein repl :start :host 0.0.0.0 :port 35543
}

repl_headless(){
  lein repl :headless :host 0.0.0.0 :port 35543
}

ring_headless(){
   lein ring server-headless 
}

conn(){
  lein repl :connect 0.0.0.0:35543
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

init(){
  #  repl_headless
  ring_headless
}

"$@"
