#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9

format(){
  $HADOOP_HOME/bin/hdfs namenode -format ${CLUSTER_NAME}
}

start_daemon(){
  # if [ "`ls -A $namedir`" == "" ]; then
  #   echo "Formatting namenode name directory: $namedir"
  #   $HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR namenode -format $CLUSTER_NAME 
  # fi
  # $HADOOP_HOME/bin/hdfs --daemon start namenode -fs hdfs://0.0.0.0:9820 # -bootstrapStandby -nonInteractive
  $HADOOP_HOME/bin/hdfs --daemon start namenode 
}

start(){
  $HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR namenode
}


main(){
  format
  # service ssh start &
  start
  # tail_dev_null
  # format
  # echo 3
  # bash -c "start"

}  

tail_dev_null(){
  tail -f /dev/null
}

hello(){
  hadoop fs -mkdir -p /hello
  hadoop fs -put hello.txt /hello
  hadoop fs -ls -R /hello
  hadoop fsck /hello/hello.txt -files -blocks -locations
}

job(){
  cd ../app_cascalog/resources/word-count-example
  sh c run1
}

"$@"
