#!/bin/bash



deep() {
    docker build -t csbooks.deep .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name deep \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)"/lab:/opt/app \
                 csbooks.deep \
                 bash
}


"$@"