#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 35543
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

init(){
    lein do clean, figwheel devcards dev
}

min(){
    lein do clean, cljsbuild once min
}

"$@"
