#!/bin/bash

export COMPOSE_CONVERT_WINDOWS_PATHS=1

# kill $(lsof -t -i:8080)
# kill -9


addlog(){
  hadoop fs -mkdir /log
  hadoop fs -put /var/log/apt/history.log /log
  hadoop fs -ls -R /log

  hadoop fsck /log/history.log -files -blocks -locations
}


"$@"
