#!/bin/bash

export COMPOSE_CONVERT_WINDOWS_PATHS=1

# kill $(lsof -t -i:8080)
# kill -9

files(){
  export PATH=${JAVA_HOME}/bin:${PATH}
  export HADOOP_CLASSPATH=${JAVA_HOME}/lib/tools.jar
  hadoop com.sun.tools.javac.Main WordCount.java
  hadoop com.sun.tools.javac.Main Word2Count.java

  jar cf wc.jar WordCount*.class
  jar cf w2c.jar Word2Count*.class


  hadoop fs -mkdir -p /user/joe/wordcount/input/
  hadoop fs -put file01 /user/joe/wordcount/input/
  hadoop fs -put file02 /user/joe/wordcount/input/

  hadoop fs -ls -R /user/joe/wordcount/input/

  hadoop fs -cat /user/joe/wordcount/input/file01
  hadoop fs -cat /user/joe/wordcount/input/file02
}

wordcount(){
  hadoop jar wc.jar WordCount /user/joe/wordcount/input /user/joe/wordcount/output3
  hadoop fs -cat /user/joe/wordcount/output3/part-r-00000

  hadoop jar w2c.jar Word2Count /user/joe/wordcount/input /user/joe/wordcount/output4
  hadoop fs -cat /user/joe/wordcount/output4/part-r-00000

}

job(){
  files
  wordcount
}

"$@"
