#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9
main(){
  # service ssh start &
  start
}
start_daemon(){
  # hdfs datanode -h
  $HADOOP_HOME/bin/hdfs --daemon start datanode 
}

start(){
  # hdfs datanode -h
  $HADOOP_HOME/bin/hdfs --config $HADOOP_CONF_DIR datanode
}

tail_dev_null(){
  tail -f /dev/null
}

"$@"
