#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 7888
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

init(){
  # https://github.com/clojure-emacs/cider/pull/2194
  # clojure -m core.tutorial
  clojure -m core.core
}

cors_service(){
  pwd
}


devnull(){
   tail -f /dev/null
}



"$@"
