#!/bin/bash

jess(){
    # java -classpath /opt/jess.jar jess.Main
    java -classpath /opt/Jess61p4/jess.jar jess.Main "$@"
}

jess_os(){
    # java -classpath /opt/jess.jar jess.Main
    java -classpath jess.jar jess.Main "$@"
}

download_jess(){
    curl -O https://manning-content.s3.amazonaws.com/download/e/839f142-236f-4866-8693-abf06add86de/friedman-hill_src_1_jess_se.zip && \
    unzip friedman-hill_src_1_jess_se.zip && \
    cp Jess61p4/jess.jar jess.jar
}


dock() {
    docker build -t csbooks.jess .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name jess \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)":/opt/app \
                 csbooks.jess \
                 bash
}


"$@"
