#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9

main(){
  start
}
start_daemon(){
  # hdfs datanode -h
  $HADOOP_HOME/bin/mapred --daemon start historyserver
}

start(){
  $HADOOP_HOME/bin/mapred --config $HADOOP_CONF_DIR historyserver
}


tail_dev_null(){
  tail -f /dev/null
}


"$@"
