#!/bin/bash

repl(){
  clj -R:nREPL -m nrepl.cmdline -i
}

connect7888(){
  clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.3"}}}' -m nrepl.cmdline --connect --host 127.0.0.1 --port 7888
}

nrepl_cljs(){
  clj -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"
}

dev(){
  # https://github.com/clojure-emacs/cider/pull/2194
  # clojure -m core.tutorial
  clojure -m core.core
}

cors_service(){
  pwd
}


devnull(){
   tail -f /dev/null
}

dock() {
    docker build -t csbooks.jess .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name jess \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)":/opt/app \
                 csbooks.jess \
                 bash
}



"$@"
