#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9

main(){
  # wrapdocker
  service ssh start &
  start
}
start_daemon(){
  # hdfs datanode -h
  $HADOOP_HOME/bin/yarn --daemon start nodemanager
}
start(){
  $HADOOP_HOME/bin/yarn --config $HADOOP_CONF_DIR nodemanager
}

pull(){
  REGISTRY_HOST=registry:5000
  echo $REGISTRY_HOST/$1
  docker pull $REGISTRY_HOST/$1
}


dev(){
  lein run-dev
}


job(){
  cd ../apps//word-count-example
  sh c job
}


"$@"
