#!/bin/bash


# kill $(lsof -t -i:8080)
# kill -9

main(){
  wrapdocker
  start
}
start_daemon(){
  # hdfs datanode -h
  $HADOOP_HOME/bin/yarn --daemon start nodemanager
}
start(){
  $HADOOP_HOME/bin/yarn --config $HADOOP_CONF_DIR nodemanager
}



"$@"
